## STEP 1:  Importing Libraries.

In [ ]:
 
import pandas as pd
import seaborn as sns
import matplotlib as plt

Matplotlib is building the font cache; this may take a moment.

## STEP 2: Loading the dataset.

In [ ]:

# Reading the supplements dataset
sales_data = pd.read_excel("/Users/luxdevhq/Desktop/Data Science CH07/EDA/data/dirty_supplement_sales_data_2020.xlsx")

## STEP 3: Inspecting the Data.

In [ ]:

# Inspecting the top 5 rows
print(f"Top 5 rows: {display(sales_data.head())}")

# Inspecting the last 5 rows. 
print(f"Last 5 rows: {display(sales_data.tail())}")

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
0,2020-10-07,Sleep Aids,ImmunoPro,NaN,1.0,$10.99,105.0,0.000,Instore,Los Angeles
1,2020-09-16,Vitamins,MuscleMax,NaN,-1.0,NaN,0.0,NaN,Mob App,Houston
2,2020-11-11,Immunity Boosters,Slim F@st,15.0,-1.0,15,NaN,225.000,Online,Chicago
3,2020-11-04,Energy Drinks,PowerFuel,14.0,0.0,$10.99,25.0,115.395,Online,new york
4,2020-06-03,Vitamins,SuperV!ta,NaN,NaN,$10.99,50.0,0.000,Mobile App,new york

Top 5 rows: None

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
3095,2020-09-16,Immunity Boosters,SuperV!ta,10.0,2.0,NaN,25.0,NaN,In-Store,Chicago
3096,2020-08-12,Vitamins,DreamRest,25.0,0.0,NaN,25.0,NaN,onlien,New York
3097,2020-10-21,Immunity Boosters,SuperV!ta,NaN,-1.0,$10.99,25.0,0.0,Mobile App,Chi-Town
3098,2020-02-19,Weight Loss,SuperVita,NaN,NaN,NaN,NaN,NaN,Instore,Chicago
3099,2020-08-26,Protein,PowerFuel,NaN,0.0,15,0.0,0.0,Mobile App,Phoenix

Last 5 rows: None

In [45]:
# Getting the shape of the dataset. 
sales_data.shape

(3100, 10)

In [46]:
# Summary info about the dataset
print(sales_data.info())

print(sales_data.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              3100 non-null   object
 1   Product Category  3100 non-null   object
 2   Product Name      3100 non-null   object
 3   Units Sold        1551 non-null   float64
 4   Units Returned    2495 non-null   float64
 5   Price             2457 non-null   object
 6   Discount (%)      2651 non-null   float64
 7   Revenue           2457 non-null   float64
 8   Platform          3100 non-null   object
 9   Location          3100 non-null   object
dtypes: float64(4), object(6)
memory usage: 242.3+ KB
None
Date                 object
Product Category     object
Product Name         object
Units Sold          float64
Units Returned      float64
Price                object
Discount (%)        float64
Revenue             float64
Platform             object
Location             object
dtype: object

In [47]:
# Summary statistics about the dataset. 
# i) Numerical columns. 
sales_data.describe().T # you can also use .transponse()

                 count        mean         std   min   25%   50%    75%    max
Units Sold      1551.0   24.514507   14.398598   1.0  11.5  24.0   37.0   50.0
Units Returned  2495.0    0.478557    1.120023  -1.0  -1.0   0.0    1.0    2.0
Discount (%)    2651.0   35.403621   35.162792   0.0  10.0  25.0   50.0  105.0
Revenue         2457.0  101.290307  159.300390 -37.5   0.0   0.0  180.0  735.0

In [48]:
# ii) Categorical columns 
sales_data.describe(include='object').T # include='object'

                 count unique         top freq
Date              3100    104  2020-05-20   68
Product Category  3100      6     Protein  555
Product Name      3100      8   Slim F@st  409
Price             2457      4   12.50 USD  642
Platform          3100      6     Instore  537
Location          3100      8        L.A.  421

In [49]:
# View the columns. 
sales_data.columns

Index(['Date', 'Product Category', 'Product Name', 'Units Sold',
       'Units Returned', 'Price', 'Discount (%)', 'Revenue', 'Platform',
       'Location'],
      dtype='object')

In [50]:
# Check the null summary 
sales_data.isnull().sum()

Date                   0
Product Category       0
Product Name           0
Units Sold          1549
Units Returned       605
Price                643
Discount (%)         449
Revenue              643
Platform               0
Location               0
dtype: int64

In [51]:
# STEP 4: Data Cleaning
# Standardizing the column names. Why standardization matters.
# 1. Prevent Code Errors: Python can fail if names contain hidden sapces, trailing whitespaces or special characters. 
# Simplifies merging: Joining datasets requires matching key columns(e.g dataset1 StudentID vs Student Id) p.d.merge(datset1, dataset2, on='')
# Ehances readability.  
# Common pracices in standardization.  
# i) Use lowercase letters
# ii) Replace spaces with undersscores. 
# iii) Do away with special characters

In [52]:
# a) Stripping any preceding or trailing spaces. 
sales_data.columns = sales_data.columns.str.strip()

In [53]:
# b). set the column names to lowercase
sales_data.columns = sales_data.columns.str.lower()

In [54]:
# c). Remove any spaces between wordds and replace with underscores. 
sales_data.columns = sales_data.columns.str.replace(" ", "_")

In [55]:
# d). Remove special characters(replace the % in the discount column with 'percent')
sales_data = sales_data.rename(columns = {'discount_(%)':'discount_percentage'})

In [56]:
sales_data.columns

Index(['date', 'product_category', 'product_name', 'units_sold',
       'units_returned', 'price', 'discount_percentage', 'revenue', 'platform',
       'location'],
      dtype='object')

In [57]:
# Note: Instead of wrting indiviadual conversions, you can use the code below.
# sales_data.columns = sales.data.columns.str.strip().str.lower().str.replace(" ", "_").str.replace('discount_(%)', 'discount_percentage', regex=False)

In [58]:
# Standardise Data Type
# Common problems assocaited with data type.  
# - Dates stored as text
# - Numbers are stored as text. 
# - Currency values stored wit the symbols.

In [59]:
sales_data.isnull().sum()

date                      0
product_category          0
product_name              0
units_sold             1549
units_returned          605
price                   643
discount_percentage     449
revenue                 643
platform                  0
location                  0
dtype: int64

In [61]:
sales_data["date"].unique()

array(['2020-10-07', '2020-09-16', '2020-11-11', '2020-11-04',
       '2020-06-03', '2020-09-09', '2020-06-17', '2020-09-23',
       '2020-10-28', '2020-04-01', '2020-11-25', '2020-02-19',
       '2020-09-02', '22/07/2020', '05/08/2020', '2020-01-29',
       '08/04/2020', '2020-11-18', '2020-04-15', '2020-07-15',
       '2020-07-29', '2020-07-08', '23/09/2020', '2020-07-01',
       '2020-10-21', '2020-04-22', '2020-01-01', '26/02/2020',
       '2020-09-30', '2020-12-23', '2020-04-08', '2020-05-27',
       '2020-03-18', '2020-06-10', '2020-05-20', '2020-06-24',
       '2020-07-22', '2020-02-05', '2020-10-14', '2020-03-11',
       '2020-04-29', '2020-03-04', '01/07/2020', '2020-05-13',
       '2020-02-12', '27/05/2020', '02/09/2020', '06/05/2020',
       '2020-12-02', '2020-08-05', '2020-05-06', '07/10/2020',
       '2020-01-08', '29/04/2020', '2020-08-26', '2020-08-19',
       '30/09/2020', '2020-12-16', '2020-12-09', '2020-03-25',
       '2020-01-15', '22/04/2020', '12/02/2020', '19/02/2020',
       '22/01/2020', '2020-08-12', '18/11/2020', '25/03/2020',
       '15/04/2020', '21/10/2020', '2020-01-22', '16/09/2020',
       '02/12/2020', '01/04/2020', '14/10/2020', '01/01/2020',
       '17/06/2020', '26/08/2020', '20/05/2020', '24/06/2020',
       '15/01/2020', '05/02/2020', '15/07/2020', '2020-02-26',
       '19/08/2020', '13/05/2020', '09/12/2020', '09/09/2020',
       '16/12/2020', '29/01/2020', '11/11/2020', '03/06/2020',
       '18/03/2020', '25/11/2020', '10/06/2020', '12/08/2020',
       '04/11/2020', '08/01/2020', '04/03/2020', '29/07/2020',
       '11/03/2020', '28/10/2020', '23/12/2020', '08/07/2020'],
      dtype=object)

In [62]:
# Converting dates to datetype 
# pd.to_datetime(df['datescolumn'], errors='coerce')

# sales_data['date'] = pd.to_datetime(sales_data["date"], errors='coerce') 
sales_data["date"] = pd.to_datetime(sales_data["date"], format='mixed', errors='coerce')

In [64]:
sales_data.dtypes

date                   datetime64[ns]
product_category               object
product_name                   object
units_sold                    float64
units_returned                float64
price                          object
discount_percentage           float64
revenue                       float64
platform                       object
location                       object
dtype: object

In [65]:
# cleaning the price column. 
sales_data["price"].unique()

array(['$10.99', nan, 15, '12.50 USD', 9.99], dtype=object)

In [67]:
# Remove the currency sign and convert to numeric format
# Dropping the currencies
sales_data["price"] = sales_data["price"].astype(str).str.replace(r'[^0-9.]', '', regex=True)

# .astype(str): Converts the entire column int text, so that the string specific manipulation method can be used.
# r[^0-9.]: The ^ inside the brackets means NOT it translates to "Find anything that is not a number (0-9) and not a decimal(.)"

# Convert the price column to numeric data type
sales_data["price"] = pd.to_numeric(sales_data["price"], errors='coerce')

In [68]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 3100 non-null   datetime64[ns]
 1   product_category     3100 non-null   object
 2   product_name         3100 non-null   object
 3   units_sold           1551 non-null   float64
 4   units_returned       2495 non-null   float64
 5   price                2457 non-null   float64
 6   discount_percentage  2651 non-null   float64
 7   revenue              2457 non-null   float64
 8   platform             3100 non-null   object
 9   location             3100 non-null   object
dtypes: datetime64[ns](1), float64(5), object(4)
memory usage: 242.3+ KB