### 17th June 2026

## Types of Data  
__What is data?__ Data is a collection of raw facts, values, measurements or observations collected for analysis   

We two main types of data:  
- Numerical/Qunatitative  
- Categorical/Qualitative  

### 1. Numerical Data(Quantitative Data)  
Numerical data is data represented using numbers.  
It can be counted or measured.  
_Numerical data has two types_  
a). Discrete data  
b). Continous data  

#### 1.1 Discrete data.  
Discrete data refers to information that can only take specific, distinct and countable values. It is obtained by counting rather than measuring. It contains only whole numbers.   
_Examples_  
Number of students, people.  

_Characteristics of discrete data_  
- Countable/you can can count it.  
- Consists of whole numbers.  
- No Decimals.  

#### 1.2 Continous data(numbers).  
Continous data is measurable numerical data. It can take any value, including decimals.  

_Examples_  
Distance, Height, Weight, Salary, Temperature  

_Characteristics_  
- Measurable i.e measured rather than counted.  
- can have decimals.  
- Infinite possible values.  

### 2. Categorical Data(Qualitative Data)  
Categorical data represents groups, names, labels or categories.   
_Examples_  
Gender, Blood Group and Marital Status.  

Categorical data has two types:
- Nominal data. 
- Ordinal data.  

#### 2.1 Nominal Data. 
Nominal data consists of categories without order.  
There's no ranking or sequence.  

_Examples_  
Gender, counties, religion, blood group.  

_Characteristics of nominal data_  
- Names/Labels. 
- No natural order or sequence.   

#### 2.2 Ordinal Data. 
Ordinal data is categorical data wit order/ranking.  

_Examples_  
Primary > High School > Bachelors > Masters > PhD

Grading system:  
A > B > C > D > E

## Descriptive Statistics. 
Descriptive statistics refers to methods used to organize, summarize, and describe data.  

__There are two major types of descriptive statistics__  
1. Measures of central tendency (mean, median, mode)  
    - Defines the centre of the data  
2. Measures of spread.(Range, IQR, Variance, Standard Deviation)  
    - How spread the data is.  

### 1. Measures of Central Tendency.  
Measures of central tendency are statistical values that find the centre value of a dataset. They summarize an entire distribution of numbers into a single representative value. 

There are three major measures:  
1. Mean  
2. Median 
3. Mode

#### 1.1 Mean. 
The mean is the average value. The sum of all the values divided by thenumber of values.  
__Advantages of mean__  
- Uses all values  
- Easy to calculate
- Commonly use  

__Disadvantages of mean__   
- Affected by outliers.  
(An outlier is a data point that sits an abnormal distance away from all other other values ina dataset)

In [ ]:
ages = [23, 24, 25, 26, 34, 21, 30] 

average_age = sum(ages)/len(ages)

print(average_age)

64.71428571428571

In [7]:
# Average age usig numpy
import numpy as np

avg_age = np.mean(ages)

print(avg_age)

26.142857142857142

In [4]:
import pandas as pd  

housing_data = pd.read_csv("/Users/luxdevhq/Desktop/Data Science CH07/Statistics/nairobi_housing_statistics_dataset.csv")

In [6]:
# Average monthly rent  
average_rent = housing_data["monthly_rent_kes"].mean() 

average_rent

np.float64(223196.0425)

#### 1.2 Median.  
The median is the middlemost value after arranging data in order(ascending).  

The main advantage of median is median is not afftected by outliers, thus useful when data has outliers.

In [ ]:
# Example of odd number values

ages = [23, 24, 25, 26, 34, 21, 30] 

# Step 1: Arrange the ages in ascending order  
ages = [21, 23, 24, 25, 26, 30, 34]  

# Final step pick the centremost value(25)

In [11]:
# Using numpy 
median_age = np.median(ages)

print(median_age)

25.0

In [12]:
# Even number of values  
ages = [21, 23, 24, 25, 26, 30, 34, 20] # 8 elements/values 

# Step 1: arrange in an ascending order. 
ages = [20, 21, 23, 24, 25, 26, 30, 34] 

# Step 2: Pick the 2 middlemost values.  
[24, 25]

median_age = (24 + 25)/2

print(median_age)

24.5

In [15]:
# Using numpy 
med_age = np.median(ages)
print(med_age)

24.5

In [16]:
# Median rent
median_rent = housing_data["monthly_rent_kes"].median() 
print(median_rent)

190307.5

In [18]:
# Testing the effects of outliers on the mean and the median. 
numbers = [1, 2, 3, 4, 5] # Numbers before outliers

# Mean before outliers  
mean1 = np.mean(numbers) 
print(f"Mean before outliers: {mean1}")

# Median before outliers  
median1 = np.median(numbers)

print(f"Median before outliers: {median1}")

# AFTER OUTLIERS 
numbers2 = [1, 2, 3, 4, 50] # Numbers after outliers
# Mean after outliers
mean2 = np.mean(numbers2)
print(f"Mean after outliers: {mean2}")
# Median after outliers
median2 = np.median(numbers2)
print(f"median after outliers: {median2}")

Mean before outliers: 3.0
Median before outliers: 3.0
Mean after outliers: 12.0
median after outliers: 3.0

#### 1.3 Mode  
The mode is the value that appears most often in the data.   
_Example_  
In most parts of Kenya, the mode for religious preference is christianity.  \

_Types of modes_  
- Unimodal - One mode
- Bimodal - Two modes. 
- Multimodal - More than 2 modes

In [ ]:
numbers = [1, 2, 3, 3, 3, 3, 4, 5, 6] # Number 3 is the mode as it is appearing most frequently

In [19]:
# most popular estate in Nairobi  
popular_estate = housing_data["estate"].mode()

print(f"The most popular estates is {popular_estate}")

The most popular estates is 0    Westlands
Name: estate, dtype: str

In [20]:
# Most popular property type in Nairobi. 
popular_property_type = housing_data["property_type"].mode()

print(popular_property_type)

0    Apartment
Name: property_type, dtype: str

### 2. Measures of Spread  
Measures of spread show how scattered or spread the data is.

In [22]:
class_a = [48, 49, 50, 51, 52]
class_a_average = np.mean(class_a)

class_b = [10, 30, 50, 70, 90]
class_b_average = np.mean(class_b)

print(f"Class A mean: {class_a_average}")
print(f"Class B mean: {class_b_average}") # Despite Class A and B having the same mean, Class B is more spread out

Class A mean: 50.0
Class B mean: 50.0

#### 2.1 Range  
Range is the difference between the largest and the smallest value.  
_Formula_  
Range = Maximum - Minimum  

- Range tells us how far the data stretches. 
 
__Limitation__ The range is highly sensitive to outliers

In [25]:
marks = [20, 40, 50, 70, 90]
# Define the maximum and the minimum 
max_number = 90
min_number = 20
# Calculate the range
range = max_number - min_number
print(range)

70

In [30]:
# Get the range for distance to cbd 
# Define the maximum and the minimum
max_distance = housing_data["distance_to_cbd_km"].max()
min_distance = housing_data["distance_to_cbd_km"].min()

print(f"Maximum distance {max_distance}km & minimum distance {min_distance}km")

# Calculate the range
distance_range = max_distance - min_distance

print("Range ",distance_range)

Maximum distance 47.6km & minimum distance 0.4km
Range  47.2

#### 2.2 Interquartile Range(IQR). 
- IQR measures spread of the middle 50% of data.  
- Since `Range` is highly sensitive to outliers, IQR ignores extreme values as it looks at the centre of the data.  

_Formula_  
IQR = Q3 - Q1  
Q1 = First Quartile(25th Perecentile).  
Q3 = Third Quartile(75th Percentile).   

IQR is useful when outliers exist.

In [31]:
marks = [10, 20, 30, 40, 50, 60, 70]

# Median 40
# Quarter 1 => 20
# Quarter 3 => 60
IQR = 60 - 20 

print(IQR)

40

In [32]:
# Example monthly rent kes 
# First Quartile  
q1 = housing_data["monthly_rent_kes"].quantile(0.25)

# Third quartile
q3 = housing_data["monthly_rent_kes"].quantile(0.75)

# Interquartile range
iqr = q3 - q1

print(f"Quarter 1 rent: {q1}")
print(f"Quarter 3 rent: {q3}")
print(f"Interqartile range: {iqr}")

Quarter 1 rent: 129188.25
Quarter 3 rent: 287698.25
Interqartile range: 158510.0

In [5]:
housing_data.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

#### 2.3 Variance  
Variance measures how far values are from the mean.  

_Analogy_  
Imagine students walking around the teacher.  
If students stand close > low variance.  (small variance means data is close together).   
If students are scattered everywhere > High variance.(large variance means the data is spread out)  

_Formula_  
Sample variance:  

$s^2 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n -1}$  


s2: Sample Variance. 
Sigma: Summation(add them up)  
xi: Each individual data point.  
xbar: Sample mean.  
n: Total number of data points   

__Important Note:__  Due to the squaring and suming, variance produces large numbers that are harder to interpret.

In [33]:
# Example 
data = {'Age':[25, 30, 35, 40],
        'Salary': [50000, 54000, 62000, 68000]}

df = pd.DataFrame(data)

df.head()

   Age  Salary
0   25   50000
1   30   54000
2   35   62000
3   40   68000

$s^2 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n - 1}$

In [37]:
# Calculate variance for age
mean_age = df["Age"].mean()
print(f"Average age: {mean_age}")  

variance = (((25 - 32.5)**2) + ((30 - 32.5)**2) + ((35 - 32.5) **2) + ((40-32.5)**2))/(4-1)

print("Variance is ", variance)

Average age: 32.5
Variance is  41.666666666666664

$$ \text{Variance} = \frac{(25 - 32.5)^2 + (30 - 32.5)^2 + (35 - 32.5)^2 + (40 - 32.5)^2}{4 - 1} $$

In [40]:
# Age variance pandas
age_var = df["Age"].var()
print("Age Variance: ", age_var)

Age Variance:  41.666666666666664

In [38]:
# Using pandas 
# Get the variance for floor size column  
floor_size_var = housing_data["floor_size_sqm"].var()

print("Floor size variance: ", floor_size_var)

Floor size variance:  236.9142426313157

In [42]:
# Using numpy  
np_floorsize_var = np.var(housing_data["floor_size_sqm"])

print(np_floorsize_var)

236.79578551000003